### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by yuan9778** [kkumatani/distant_speech_recognition#4]
Dear Kenichi,
I tried to run Single channel WPE dereverberator using the following script:
`python test_subband_dereverberator.py -i data/CMU/R1/M1005/KINECT/RAW/segmented/U1001_1M_16k_b16_c1.wav -o out/U1001_1M_16k_b16_c1.wav`

and the result is:

Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

I googled this issue and it seems caused from multiple version of python installed. I uninstalled python 3.6 but it didn't solve the problem. I'm wondering if I can get some suggestion from you.

Thanks much!

**Comment by kkumatani** [comment]
I've never had this error. Could you tell me a bit more detail:
- OS
- Python package
- Python version (python -V)
Also, could you make sure numpy works normally?

**Comment by yuan9778** [comment]
Thanks for your reply.

Never mind. I tried it on a newly build Ubuntu system and it works just fine. My macOS has like 3 versions of python, which is probably the reason causing the problem.
