### ISSUE TITLE
why OverSampledDFTAnalysisBank using a backward fft?

### ISSUE THREAD

**Issue by decentsheep** [kkumatani/distant_speech_recognition#8]
Hi, this project is so cool! It is very helpful for ASR develoment! Thank you all! I am looking the filter bank implemented in btk2.0, and it really confused me that OverSampledDFTAnalysisBank doing backward fft after a polyphase filter,

**Comment by kkumatani** [comment]
The details of filter bank design is described here:
[https://www.dropbox.com/s/2hc32piufzvm3ea/filter-bank-design.pdf?dl=0](url)

The short paper is also published in ICASSP2008:
["Filter bank design based on minimization of individual aliasing terms for minimum mutual information subband adaptive beamforming", ICASSP 2008.](https://ieeexplore.ieee.org/abstract/document/4517933)

**Comment by decentsheep** [comment]
thanks kkumatani! I made a mistake when opening this issue, I did not make a full description about my question, the complete issue is here `https://github.com/kkumatani/distant_speech_recognition/issues/9`, the first link you provide can not be opened, I looked through the second link, but It seems did not explain why a backward fft(inverse fft) adopted in analysis filter bank but not a forward fft, maybe I should research more about it

**Comment by decentsheep** [comment]
> The details of filter bank design is described here:
> [https://www.dropbox.com/s/2hc32piufzvm3ea/filter-bank-design.pdf?dl=0](url)
> 
> The short paper is also published in ICASSP2008:
> ["Filter bank design based on minimization of individual aliasing terms for minimum mutual information subband adaptive beamforming", ICASSP 2008.](https://ieeexplore.ieee.org/abstract/document/4517933)



> The details of filter bank design is described here:
> [https://www.dropbox.com/s/2hc32piufzvm3ea/filter-bank-design.pdf?dl=0](url)
> 
> The short paper is also published in ICASSP2008:
> ["Filter bank design based on minimization of individual aliasing terms for minimum mutual information subband adaptive beamforming", ICASSP 2008.](https://ieeexplore.ieee.org/abstract/document/4517933)

thanks kkumatani! I made a mistake when opening this issue, I did not make a full description about my question, the complete issue is here `https://github.com/kkumatani/distant_speech_recognition/issues/9`, the first link you provide can not be opened, I looked through the second link, but It seems did not explain why a backward fft(inverse fft) adopted in analysis filter bank but not a forward fft, maybe I should research more about it
